version: '3'
services:
  chrome-app:
    container_name: chrome-service
    image: chrome-go-server
    restart: always # ключевое свойство для автоматического перезапуска
    build:
      # Где лежит докер файл
      context: ./
    ports:
      - "8081:8081"
#    volumes:
#      - type: bind
#        source: /tmp/.X11-unix
#        target: /tmp/.X11-unix       # Пробрасываем x-ы

#      - type: bind
#        source: ./data1
#        target: /src/data
networks:
  backend-network:
    driver: bridge
